// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using YourPet.NPgsqlEfCore;

#nullable disable

namespace YourPet.NpgsqlEFCore.Migrations
{
    [DbContext(typeof(PetDbContext))]
    [Migration("20240922163135_UserToPet")]
    partial class UserToPet
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("YourPet.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Auth0Id")
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSubscribedToNewsletter")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RegistrationDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Event", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetID")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("PetID");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Medicine", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Dosage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PetID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ID");

                    b.HasIndex("PetID");

                    b.ToTable("Medicine");
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarKey")
                        .HasColumnType("text")
                        .HasColumnName("avatar_key");

                    b.Property<string>("BehaviorNotes")
                        .HasColumnType("text")
                        .HasColumnName("behavior_notes");

                    b.Property<string>("Breed")
                        .HasColumnType("text")
                        .HasColumnName("breed");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("DietaryRequirements")
                        .HasColumnType("text")
                        .HasColumnName("dietary_requirements");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Gender")
                        .HasColumnType("text")
                        .HasColumnName("gender");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("text")
                        .HasColumnName("medical_history");

                    b.Property<string>("MicrochipID")
                        .HasColumnType("text")
                        .HasColumnName("microchip_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SpecialNeeds")
                        .HasColumnType("text")
                        .HasColumnName("special_needs");

                    b.Property<string>("Species")
                        .HasColumnType("text")
                        .HasColumnName("species");

                    b.Property<string>("VaccinationRecords")
                        .HasColumnType("text")
                        .HasColumnName("vaccination_records");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.ToTable("pet", (string)null);
                });

            modelBuilder.Entity("app_user_pet_rel", b =>
                {
                    b.Property<int>("app_user_id")
                        .HasColumnType("integer");

                    b.Property<int>("pet_id")
                        .HasColumnType("integer");

                    b.HasKey("app_user_id", "pet_id");

                    b.HasIndex("pet_id");

                    b.ToTable("app_user_pet_rel");
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Event", b =>
                {
                    b.HasOne("YourPet.Domain.Entities.Pet", "Pet")
                        .WithMany("Events")
                        .HasForeignKey("PetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Medicine", b =>
                {
                    b.HasOne("YourPet.Domain.Entities.Pet", "Pet")
                        .WithMany("Medicines")
                        .HasForeignKey("PetID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("app_user_pet_rel", b =>
                {
                    b.HasOne("YourPet.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("app_user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("YourPet.Domain.Entities.Pet", null)
                        .WithMany()
                        .HasForeignKey("pet_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("YourPet.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Medicines");
                });
#pragma warning restore 612, 618
        }
    }
}
